---
title: "Review of: Migraines and Math Degrees: A Spurious Love Story"
subtitle: Original paper by Tilmann Diepenbruck, Tom Hunze
authors: Review by Rose Hörsting, Ali Yildiz, Zihang Su
format: pdf
editor: visual
---
The reviewed work has been reproduced in its entirety on a Windows machine (Windows 11 Pro, Version 24H2, Build 26100.4652) following steps below:

-   Install WSL along with the designated Linux distribution (Ubuntu 22.04 LTS)
-   Install Git
-   Install Nix within WSL
-   Enable Nix Flakes
-   Fetch data via git-annex
-   Rebuild the original paper
-   Install wslu
-   Locate rebuilt file
-   Verify rebuilt file

The reproduction procedure was smooth, as sufficient instruction for each step can be found in the posted README file. In addition, the authors provide code for automatically verifying the reproduction against the original paper, which enables immediate comparison and the output of which is in accordance with the expectation.

Executability of the reviewed work is high, as compatibility with the most widespread operating systems (Linux, MacOS, Windows) was taken into consideration by the authors when providing instruction for reproduction.

Readability of the reviewed work is high, as both the documentation (.md) and the paper itself (.pdf) are accessible in formats generally supported across platforms. 

Data used to produce the analysis are accessed through an established version control system (git-annex), which benefits findability, durability and authenticity thereof.

The reviewed work is licenced under CC0 1.0 Universal, which allows others to copy, modify, publish, use, compile, sell, or distribute the work for any purpose. thereby ensuring complete openness, accessibility and reusability of methods as well as results involved.

Understandability of the reviewed work varies depending on how familiar readers are with the functionality of certain software, in this case Nix the package manager in particular. When rebuilt with a single line of command, there is no apparent 1-to-1 correspondence between code and code-generated analytic outcome (statistics and visualization thereof) in the paper, which is to be manually inspected in a separated python script and TeX file not specifically mentioned in documentation. In certain disciplines, formats enabling seamless integration of code and analytic outcome (e.g. knitr, Juypter Notebook) are more prevalent, which are not necessarily a better, but definitely a viable option.

Dependencies on external libraries of code used to generate analytic outcome is not as well documented as instruction for reproduction and content references in the reviewed work. A common practice to ensure transparency of code dependencies is to have a dedicated BibTeX file unifying citations of both content references and external code libraries.

Overall, computational reproducibility of the reviewed work is high thanks to well-structured reproduction procedure and detailed documentation.
